version: '3'
services:
  postgres:
    image: postgres:9-alpine
    container_name: postgres-softplan
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - softplan
volumes:
  pgdata:

networks:
  softplan: